version: '3.6'
services:

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: ./
      dockerfile: docker/local/workers/Dockerfile
    depends_on:
      - redis
    command: celery -A camnode.workers worker --loglevel=debug
    environment:
      ENV: local
      QUEUE_REDIS_HOST: redis
      QUEUE_BROKER_REDIS_DB: 0
      QUEUE_RESULTS_REDIS_DB: 1
    volumes:
      - type: bind
        source: ./
        target: /app

  collector:
    build:
      context: ./
      dockerfile: docker/local/collector/Dockerfile
    depends_on:
      - celery
    command: python decawaves.py
    privileged: true
    network_mode: host
    environment:
      ENV: local
      QUEUE_REDIS_HOST: localhost
      QUEUE_BROKER_REDIS_DB: 0
      QUEUE_RESULTS_REDIS_DB: 1
    volumes:
      - type: bind
        source: ./
        target: /app

  capture:
    build:
      context: ./
      dockerfile: docker/local/capture/Dockerfile
    depends_on:
      - celery
    command: python run_capture.py
    privileged: true
    network_mode: host
    environment:
      ENV: local
      QUEUE_REDIS_HOST: localhost
      QUEUE_BROKER_REDIS_DB: 0
      QUEUE_RESULTS_REDIS_DB: 1
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./outputs
        target: /out
