---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway

# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   namespace: gateway
#   name: gateway-redis
# spec:
#   replicas: 1
#   template:
#     metadata:
#       namespace: gateway
#       labels:
#         app: gateway-redis
#     spec:
#       containers:
#         - name: gateway-redis
#           image: redis:5.0.2
#           imagePullPolicy: "Always"
#           ports:
#             - containerPort: 6379


