---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classroom-scheduler
  namespace: classroom
automountServiceAccountToken: true


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: classroom-scheduler
  namespace: classroom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: classroom-scheduler
  namespace: classroom


---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: classroom
  name: scheduler
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: classroom-scheduler
          automountServiceAccountToken: true
          containers:
          - name: scheduler
            image: wildflowerschools/k8s-task-scheduler:v4
            # command: ["sleep", "3000"]
            env:
            - name: CONFIG_PATH
              value: "/app/config/schedule.yaml"
            - name: K8S_CLUSTER_NAME
              value: "wework"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: schedule-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: schedule-config
  namespace: classroom
data:
  schedule.yaml: |
    timezone: "US/Eastern"
    events: []
    schedules:
    - start: "08:00"
      end: "16:30"
      days: [0, 1, 2, 3, 4]
      actions:
        start: create-shoe-collector
        end: delete-shoe-collector
        probe: test-shoe-collector
    - start: "08:00"
      end: "16:30"
      days: [0, 1, 2, 3, 4]
      actions:
        start: create-capture
        end: delete-capture
        probe: test-capture
    actions:
      create-shoe-collector:
        type: create
        manifest: config/shoes.yaml
      delete-shoe-collector:
        type: delete
        resources:
        - ["classroom", "daemon-set", "shoe-collector"]
      test-shoe-collector:
        type: status
        resource: ["classroom", "daemon-set", "shoe-collector"]
        fields:
        - name: current_number_scheduled
          value: 0
          op: GTE
        on_failure: create-shoe-collector
      create-capture:
        type: create
        manifest: config/camera.yaml
      delete-capture:
        type: delete
        resources:
        - ["classroom", "daemon-set", "capture"]
      test-capture:
        type: status
        resource: ["classroom", "daemon-set", "capture"]
        fields:
        - name: current_number_scheduled
          value: 0
          op: GTE
        on_failure: create-capture
  camera.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      namespace: classroom
      name: capture
      labels:
        name: capture
    spec:
      selector:
        matchLabels:
          name: capture
      template:
        metadata:
          namespace: classroom
          labels:
            name: capture
        spec:
          nodeSelector:
            wildflower-type: camera
          containers:
          - image: "wildflowerschools/classroom-node-capture:v27"
            name: capture
            securityContext:
              privileged: true
            env:
              - name: MINIO_KEY
                value: "wildflower-classroom"
              - name: MINIO_SECRET
                value: "892347428463011457756120837563764010019"
              - name: MINIO_BUCKET_NAME
                value: "videos"
              - name: MINIO_URL
                value: "minio-service.classroom.svc.cluster.local:9000"
            volumeMounts:
            - name: boot
              mountPath: /boot
            - name: video-buffer
              mountPath: /out
          volumes:
            - name: boot
              hostPath:
                path: /boot
                type: Directory
            - name: video-buffer
              hostPath:
                path: /data
                type: Directory
  shoes.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      namespace: classroom
      name: shoe-collector
      labels:
        name: shoe-collector
    spec:
      selector:
        matchLabels:
          name: shoe-collector
      template:
        metadata:
          namespace: classroom
          labels:
            name: shoe-collector
        spec:
          hostNetwork: true
          nodeSelector:
            wf-collector: shoe
          containers:
          - image: "wildflowerschools/collectors:shoes-v15"
            name: shoe-collector
            securityContext:
              privileged: true
            ports:
            - containerPort: 8000
            env:
            - name: HONEYCOMB_URI
              value: https://honeycomb.api.wildflower-tech.org/graphql
            - name: HONEYCOMB_TOKEN_URI
              value: https://wildflowerschools.auth0.com/oauth/token
            - name: HONEYCOMB_AUDIENCE
              value: https://honeycomb.api.wildflowerschools.org
            envFrom:
              - secretRef:
                  name: honeycomb-client-settings
            volumeMounts:
            - name: data
              mountPath: /data
            - name: boot-volume
              mountPath: /boot
            - name: dev
              mountPath: /dev
            - name: config-volume
              mountPath: /app/mac_addresses.txt
              subPath: macs
          volumes:
            - name: data
              hostPath:
                path: /usr/lib/wildflower/
                type: Directory
            - name: dev
              hostPath:
                path: /dev
                type: Directory
            - name: config-volume
              configMap:
                name: shoes-config
            - name: boot-volume
              hostPath:
                path: /boot
                type: Directory


---
apiVersion: v1
data:
  macs: |
    c0:ed:12:ae:fe:72
    cc:05:d5:41:6e:0b
    d2:8c:28:c9:0a:bc
    d8:4c:3c:d0:73:5f
    de:d5:97:f9:0e:92
    df:bd:99:89:30:d8
    e8:f5:88:e4:80:ab
    ea:8d:a1:97:3a:93
    ed:1b:07:0f:2d:5f
    f1:41:fd:02:85:b4
    cc:df:e6:16:75:d5
    f7:37:32:af:e0:45
    e2:eb:1a:15:64:35
    f0:d5:05:08:84:32
    d8:35:bd:ee:df:63
    e9:4b:27:34:6d:2d
    f5:c5:6e:a1:4b:e5
    e6:ea:40:15:dc:e2
    de:f5:11:7c:53:1b
    ee:bc:19:eb:4c:c4
    cf:f4:7e:01:1c:0b
    ee:40:8d:24:48:79
    ea:68:60:a0:e5:22
    d3:1e:47:9d:32:90
    e1:8f:6e:ea:94:9e
    f6:b7:22:d4:ea:99
    f4:b3:75:53:2f:3d
kind: ConfigMap
metadata:
  name: shoes-config
  namespace: classroom
