---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: classroom
  name: shoe-collector
  labels:
    name: shoe-collector
spec:
  selector:
    matchLabels:
      name: shoe-collector
  template:
    metadata:
      namespace: classroom
      labels:
        name: shoe-collector
    spec:
      hostNetwork: true
      nodeSelector:
        wf-collector: shoe
      containers:
      - image: "wildflowerschools/collectors:shoes-v15"
        name: shoe-collector
        command: ["sh", "/app/run-honeycomb.sh"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 8000
        env:
        - name: HONEYCOMB_URI
          value: https://honeycomb.api.wildflower-tech.org/graphql
        - name: HONEYCOMB_TOKEN_URI
          value: https://wildflowerschools.auth0.com/oauth/token
        - name: HONEYCOMB_AUDIENCE
          value: https://honeycomb.api.wildflowerschools.org
        envFrom:
          - secretRef:
              name: honeycomb-client-settings
        volumeMounts:
        - name: data
          mountPath: /data
        - name: boot-volume
          mountPath: /boot
        - name: dev
          mountPath: /dev
        - name: config-volume
          mountPath: /app/mac_addresses.txt
          subPath: macs
      volumes:
        - name: data
          hostPath:
            path: /usr/lib/wildflower/
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: config-volume
          configMap:
            name: shoes-config
        - name: boot-volume
          hostPath:
            path: /boot
            type: Directory

---
apiVersion: v1
data:
  macs: |
    c0:ed:12:ae:fe:72
    cc:05:d5:41:6e:0b
    d2:8c:28:c9:0a:bc
    d8:4c:3c:d0:73:5f
    de:d5:97:f9:0e:92
    df:bd:99:89:30:d8
    e8:f5:88:e4:80:ab
    ea:8d:a1:97:3a:93
    ed:1b:07:0f:2d:5f
    f1:41:fd:02:85:b4
    cc:df:e6:16:75:d5
    f7:37:32:af:e0:45
    e2:eb:1a:15:64:35
    f0:d5:05:08:84:32
    d8:35:bd:ee:df:63
    e9:4b:27:34:6d:2d
    f5:c5:6e:a1:4b:e5
    e6:ea:40:15:dc:e2
    de:f5:11:7c:53:1b
    ee:bc:19:eb:4c:c4
    cf:f4:7e:01:1c:0b
    ee:40:8d:24:48:79
    ea:68:60:a0:e5:22
    d3:1e:47:9d:32:90
    e1:8f:6e:ea:94:9e
    f6:b7:22:d4:ea:99
    f4:b3:75:53:2f:3d

kind: ConfigMap
metadata:
  name: shoes-config
  namespace: classroom
