---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: tick
  name: pistats-collector
  labels:
    name: pistats-collector
spec:
  selector:
    matchLabels:
      name: pistats-collector
  template:
    metadata:
      namespace: tick
      labels:
        name: pistats-collector
    spec:
      hostNetwork: true
      nodeSelector:
        wildflower-type: camera
      containers:
      - image: "wildflowerschools/collectors:pistats-v2"
        name: pistats-collector
        command: ["python", "-c", "import time\nwhile True:\n    time.sleep(3)"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: bin
          mountPath: /app/bin
        - name: sys
          mountPath: /app/sys
      volumes:
        - name: bin
          hostPath:
            path: /usr/bin/
            type: Directory
        - name: sys
          hostPath:
            path: /sys/devices/system/
            type: Directory
