---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: classroom
  name: tray-collector
  labels:
    name: tray-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tray-collector
  template:
    metadata:
      namespace: classroom
      labels:
        name: tray-collector
    spec:
      hostNetwork: true
      nodeSelector:
        wf-collector: tray
      containers:
      - image: "wildflowerschools/collectors:trays-v1"
        name: tray-collector
        command: ["python", "-m", "tray_sensor.tools.tray_sensor_app", "-d", "/data/", "-o", "capucine_tray_sensors", "-l", "DEBUG"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /data
        - name: dev
          mountPath: /dev
      volumes:
        - name: data
          hostPath:
            path: /usr/lib/wildflower/
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
