apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-s3
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
        - name: fluentd-s3
          image: fluent/fluentd-kubernetes-daemonset:v1.14.6-debian-s3-amd64-1.1
          env:
            - name: S3_OBJECT_KEY_FORMAT
              value: "$(S3_CLASSROOM_NAME)/%Y/%m/%d/cluster-log-%{index}.%{file_extension}"
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
            - name: S3_TIMEKEY
              value: "600" # Upload logs every 10 minutes
            - name: FLUENTD_CONTAINER_TAIL_PATH
              value: '/var/log/containers/cuwb-udp-listener*.log' # Container logs take on the format <<POD_NAME>>_<<NAMESPACE>>_<<CONTAINER_NAME>>_<<ID>>
          envFrom:
            - configMapRef:
                name: kube-logging-aws-s3-write-auth-config
            - configMapRef:
                name: kube-logging-fluentd-s3-config
            - secretRef:
                name: kube-logging-aws-s3-write-auth-secret
          resources:
            limits:
              memory: 400Mi
              cpu:  300m
            requests:
              cpu: 300m
              memory: 400Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-s3-config
              mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-s3-config
          configMap:
            name: kube-logging-fluentd-s3-config
      nodeSelector:
        wf-type: "control"