---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-s3-scheduler
  namespace: classroom
automountServiceAccountToken: true


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-s3-scheduler
  namespace: classroom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fluentd-s3-scheduler
  namespace: classroom


---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: classroom
  name: fluentd-s3-scheduler
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              effect: NoSchedule
          nodeSelector:
            wf-type: "control"
          serviceAccountName: fluentd-s3-scheduler
          automountServiceAccountToken: true
          containers:
          - name: scheduler
            image: wildflowerschools/k8s-task-scheduler:v12
            env:
            - name: CONFIG_PATH
              value: "/app/config/schedule.yaml"
            - name: K8S_CLUSTER_NAME
              value: "wework"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: fluentd-s3-schedule-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: fluentd-s3-schedule-config
  namespace: classroom
data:
  schedule.yaml: |
    timezone: $TIMEZONE
    events: []
    schedules:
    - start: "07:00"
      end: "21:00"
      days: [0, 1, 2, 3, 4]
      actions:
        start: scale-up-log-capture
        end: scale-down-log-capture
        probe: scale-up-log-capture
        terminate: scale-down-log-capture
    actions:
      scale-up-log-capture:
        type: patch
        resource: ["kube-logging", "daemon-set", "fluentd-s3"]
        patch:
        - { "op": "replace", "path": "/spec/template/spec/nodeSelector/wf-type", "value": "control" }
      scale-down-log-capture:
        type: patch
        resource: ["kube-logging", "daemon-set", "fluentd-s3"]
        patch:
        - { "op": "replace", "path": "/spec/template/spec/nodeSelector/wf-type", "value": "non-existent" }
