---
apiVersion: v1
kind: Service
metadata:
  namespace: classroom
  name: minio
spec:
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: classroom
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 1
  template:
    metadata:
      namespace: classroom
      labels:
        app: minio
    spec:
      nodeSelector:
        wf-type: "control"
      containers:
      - name: minio
        env:
        - name: MINIO_REGION
          value: us-east-1
        - name: MINIO_ACCESS_KEY
          value: "wildflower-classroom"
        - name: MINIO_SECRET_KEY
          value: "892347428463011457756120837563764010019"
        image: "minio/minio"
        command:
          - minio
          - server
          - /data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
