---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: classroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      namespace: classroom
      labels:
        app: redis
    spec:
      containers:
        - name: redis-queue
          image: redis:5.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: classroom
  labels:
    app: redis
spec:
  type: LoadBalancer
  ports:
  - port: 6390
    targetPort: 6379
  selector:
    app: redis

