---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classroom-scheduler
  namespace: classroom
automountServiceAccountToken: true


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: classroom-scheduler
  namespace: classroom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: classroom-scheduler
  namespace: classroom


---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: classroom
  name: scheduler
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: classroom-scheduler
          automountServiceAccountToken: true
          containers:
          - name: scheduler
            image: wildflowerschools/k8s-task-scheduler:v10
            # command: ["sleep", "3000"]
            env:
            - name: CONFIG_PATH
              value: "/app/config/schedule.yaml"
            - name: K8S_CLUSTER_NAME
              value: "wework"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: schedule-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: schedule-config
  namespace: classroom
data:
  schedule.yaml: |
    timezone: "US/Pacific"
    events: []
    schedules:
    - start: "08:00"
      end: "16:30"
      days: [0, 1, 2, 3, 4]
      actions:
        start: create-capture
        end: delete-capture
        probe: test-capture
    actions:
      create-capture:
        type: create
        manifest: config/camera.yaml
      delete-capture:
        type: delete
        resources:
        - ["classroom", "daemon-set", "capture"]
      test-capture:
        type: status
        resource: ["classroom", "daemon-set", "capture"]
        fields:
        - name: current_number_scheduled
          value: 0
          op: GTE
        on_failure: create-capture
  camera.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      namespace: classroom
      name: capture
      labels:
        name: capture
    spec:
      selector:
        matchLabels:
          name: capture
      template:
        metadata:
          namespace: classroom
          labels:
            name: capture
        template:
          metadata:
            namespace: classroom
            labels:
              name: capture
          spec:
            dnsPolicy: ClusterFirstWithHostNet
            enableServiceLinks: true
            hostNetwork: true
            nodeSelector:
              wildflower-type: camera
              wf-camera-type: v2
            containers:
            - image: "wildflowerschools/classroom-node-capture:v45"
              name: capture
              securityContext:
                privileged: true
              command: ["python", "run_capture.py"]
              env:
                - name: MINIO_KEY
                  value: "wildflower-classroom"
                - name: MINIO_SECRET
                  value: "892347428463011457756120837563764010019"
                - name: MINIO_BUCKET_NAME
                  value: "videos"
                - name: MINIO_URL
                  value: "minio.classroom:9000"
                - name: CAMERA_V_FLIP
                  value: "yes"
                - name: CAMERA_H_FLIP
                  value: "yes"
              volumeMounts:
              - name: boot
                mountPath: /boot
              - name: video-buffer
                mountPath: /out
            imagePullSecrets:
            - name: regcred
            volumes:
              - name: boot
                hostPath:
                  path: /boot
                  type: Directory
              - name: video-buffer
                hostPath:
                  path: /data
                  type: Directory
      ---
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        namespace: classroom
        name: capture-hq
        labels:
          name: capture-hq
      spec:
        selector:
          matchLabels:
            name: capture-hq
        template:
          metadata:
            namespace: classroom
            labels:
              name: capture-hq
          spec:
            dnsPolicy: ClusterFirstWithHostNet
            enableServiceLinks: true
            hostNetwork: true
            nodeSelector:
              wildflower-type: camera
              wf-camera-type: HQ
            containers:
            - image: "wildflowerschools/classroom-node-capture:v45"
              name: capture-hq
              securityContext:
                privileged: true
              command: ["python", "run_capture.py"]
              env:
                - name: MINIO_KEY
                  value: "wildflower-classroom"
                - name: MINIO_SECRET
                  value: "892347428463011457756120837563764010019"
                - name: MINIO_BUCKET_NAME
                  value: "videos"
                - name: MINIO_URL
                  value: "minio.classroom:9000"
                - name: CAMERA_ISO_SETTING
                  value: "1500"
                - name: CAMERA_EXPOSURE_MODE
                  value: "backlight"
                - name: CAMERA_SHUTTER_SPEED
                  value: "40000"
                - name: CAMERA_H_FLIP
                  value: "yes"
                - name: CAMERA_V_FLIP
                  value: "yes"
              volumeMounts:
              - name: boot
                mountPath: /boot
              - name: video-buffer
                mountPath: /out
            imagePullSecrets:
            - name: regcred
            volumes:
              - name: boot
                hostPath:
                  path: /boot
                  type: Directory
              - name: video-buffer
                hostPath:
                  path: /data
                  type: Directory
