---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classroom-scheduler
  namespace: classroom
automountServiceAccountToken: true


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: classroom-scheduler
  namespace: classroom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: classroom-scheduler
  namespace: classroom


---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: classroom
  name: scheduler
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: classroom-scheduler
          automountServiceAccountToken: true
          containers:
          - name: scheduler
            image: wildflowerschools/k8s-task-scheduler:v5
            # command: ["sleep", "3000"]
            env:
            - name: CONFIG_PATH
              value: "/app/config/schedule.yaml"
            - name: K8S_CLUSTER_NAME
              value: "wework"
            volumeMounts:
            - name: config-volume
              mountPath: /app/config
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: schedule-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: schedule-config
  namespace: classroom
data:
  schedule.yaml: |
    timezone: "US/Eastern"
    events: []
    schedules:
    - start: "08:00"
      end: "16:30"
      days: [0, 1, 2, 3, 4]
      actions:
        start: create-capture
        end: delete-capture
        probe: test-capture
    actions:
      create-capture:
        type: create
        manifest: config/camera.yaml
      delete-capture:
        type: delete
        resources:
        - ["classroom", "daemon-set", "capture"]
      test-capture:
        type: status
        resource: ["classroom", "daemon-set", "capture"]
        fields:
        - name: current_number_scheduled
          value: 0
          op: GTE
        on_failure: create-capture
  camera.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      namespace: classroom
      name: capture
      labels:
        name: capture
    spec:
      selector:
        matchLabels:
          name: capture
      template:
        metadata:
          namespace: classroom
          labels:
            name: capture
        spec:
          dnsPolicy: ClusterFirstWithHostNet
          enableServiceLinks: true
          hostNetwork: true
          nodeSelector:
            wildflower-type: camera
          containers:
          - image: "wildflowerschools/classroom-node-capture:v27"
            name: capture
            securityContext:
              privileged: true
            # command: ["python", "-c", "import time\nwhile True:\n    time.sleep(3)"]
            env:
              - name: MINIO_KEY
                value: "wildflower-classroom"
              - name: MINIO_SECRET
                value: "892347428463011457756120837563764010019"
              - name: MINIO_BUCKET_NAME
                value: "videos"
              - name: MINIO_URL
                value: "minio.classroom:9000"
            volumeMounts:
            - name: boot
              mountPath: /boot
            - name: video-buffer
              mountPath: /out
          volumes:
            - name: boot
              hostPath:
                path: /boot
                type: Directory
            - name: video-buffer
              hostPath:
                path: /data
                type: Directory
