# ---
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   namespace: classroom
#   name: shell
#   labels:
#     name: shell
# spec:
#   selector:
#     matchLabels:
#       name: shell
#   template:
#     metadata:
#       namespace: classroom
#       labels:
#         name: shell
#     spec:
#       dnsPolicy: ClusterFirstWithHostNet
#       enableServiceLinks: true
#       hostNetwork: false
#       containers:
#       - image: "python:3.8.5"
#         name: shell
#         command: ["python", "-c", "import time\nwhile True:\n    time.sleep(3)"]
#         volumeMounts:
#         - name: root
#           mountPath: /root
#       volumes:
#         - name: root
#           hostPath:
#             path: /
#             type: Directory

# ---
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   namespace: classroom
#   name: dnsutils
#   labels:
#     name: dnsutils
# spec:
#   selector:
#     matchLabels:
#       name: dnsutils
#   template:
#     metadata:
#       namespace: classroom
#       labels:
#         name: dnsutils
#     spec:
#       dnsPolicy: ClusterFirstWithHostNet
#       enableServiceLinks: true
#       hostNetwork: false
#       containers:
#       - name: dnsutils
#         image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
#         command:
#           - sleep
#           - "3600"
#         imagePullPolicy: IfNotPresent
#       restartPolicy: Always